version: "3"

services:
  server:
    image: srcrs/rss-reader:latest
    container_name: rss-reader
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/index.html:/app/index.html"
      - "$PWD/db:/app/db"
      - "$PWD/config.json:/app/config.json"
